// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Autogenerated so task-based user guide pages can be added or renamed
  // without breaking the build. Control ordering with `sidebar_position`
  // front matter in each doc (falls back to alphabetical).
  userGuide: [
    {
      type: "autogenerated",
      dirName: "user-guide",
    },
  ],

  codebaseDocs: [
    {
      type: "category",
      label: "Codebase Docs",
      link: { type: "doc", id: "codebase/overview" },
      items: [
        {
          type: "category",
          label: "Architecture",
          link: { type: "doc", id: "codebase/architecture/overview" },
          items: [
            "codebase/architecture/startup-sequence",
            "codebase/architecture/camera-system",
            "codebase/architecture/sse-realtime",
          ],
        },
        {
          type: "category",
          label: "Pipelines",
          link: { type: "doc", id: "codebase/pipelines/overview" },
          items: [
            "codebase/pipelines/configuration",
            "codebase/pipelines/operation-definitions",
            "codebase/pipelines/secondary-operations",
            "codebase/pipelines/flow-manager",
            "codebase/pipelines/add-operation",
          ],
        },
        {
          type: "category",
          label: "Device Management",
          link: { type: "doc", id: "codebase/device-management/overview" },
          items: [
            "codebase/device-management/compute-pool",
            "codebase/device-management/devices",
          ],
        },
        {
          type: "category",
          label: "WebUI",
          link: { type: "doc", id: "codebase/webui/overview" },
          items: [
            "codebase/webui/backend",
            "codebase/webui/frontend",
            "codebase/webui/api",
          ],
        },
        {
          type: "category",
          label: "Extension Points",
          link: { type: "doc", id: "codebase/extension-points/overview" },
          items: [
            "codebase/extension-points/new-operation",
            "codebase/extension-points/new-device",
            "codebase/extension-points/rust-modules",
            "codebase/extension-points/new-ui-tab",
          ],
        },
        {
          type: "category",
          label: "Data Systems",
          link: { type: "doc", id: "codebase/data-systems/overview" },
          items: [
            "codebase/data-systems/flatpack-schema",
            "codebase/data-systems/networktables",
          ],
        },
        "codebase/testing",
      ],
    },
  ],
};

export default sidebars;
